# .github/workflows/ci_cd.yml

name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: iterative/setup-cml@v2
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run main file
      run: |
        python main.py
    
    
      
        

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |

        echo "# First Line of our report" >> report.md
        echo "## Bar Plots" >> report.md
        echo '![](./bars.png "Bar plot")' >> report.md
        echo "## Line Plots" >> report.md
        echo '![](./lines.png "Bar plot")' >> report.md

        cml comment create report.md